OBSTACLE_AVOID = False
MULTIPLE_OBSTACLE_AVOID = False
RADAR_AVOID = False
N_OBSTACLES = 0
BUFFER_DISTANCE = 0.0


#NLP solver options
MAX_ITER = 1500
MAX_TIME = 0.1
PRINT_LEVEL = 2
ACCEPT_TOL = 1e-2
ACCEPT_OBJ_TOL = 1e-2   
PRINT_TIME = 0


#Target options
TARGET_DISCHARGE_RATE = 0.1